name: CI

on: [push]

jobs:
    lint:
        name: "Lint (OS: ${{ matrix.os }})"
        runs-on: ${{ matrix.os }}
        timeout-minutes: 60
        strategy:
            matrix:
                os: [macOS-latest, windows-2019, ubuntu-18.04]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 8.x
              uses: actions/setup-node@v1
              with:
                  node-version: "8.x"
            - name: Install dependencies
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: install
            - name: Running linter
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: lint --ignore-pattern '/examples/'

    test:
        name: "Unit-tests (OS: ${{ matrix.os }})"
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macOS-latest, windows-2019, ubuntu-18.04]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 8.x
              uses: actions/setup-node@v1
              with:
                  node-version: "8.x"
            - name: Install dependencies
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: install
            - name: Running tests
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: test --coverage
            - name: Check coverage
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
