name: CI

on: [push]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 8.x
              uses: actions/setup-node@v1
              with:
                  node-version: "8.x"
            - name: Install yarn
              uses: borales/actions-yarn@v2.0.0
            - name: Install dependencies
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: install

    lint:
        name: Lint
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Running linter
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: lint -- --ignore-pattern '/examples/'

    test:
        name: Tests
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Running tests
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: test -- --coverage
            - name: Coverage
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: coveralls
